"""empty message

Revision ID: 166f5e2a6c79
Revises: ab9b88c59436
Create Date: 2020-05-08 18:17:19.914862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166f5e2a6c79'
down_revision = 'ab9b88c59436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address1', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('facebook_link1', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('image_link1', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('website1', sa.String(), nullable=True))
    op.drop_column('artist', 'address')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'facebook_link')
    op.add_column('venue', sa.Column('address1', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('facebook_link1', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('image_link1', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('website1', sa.String(), nullable=True))
    op.drop_column('venue', 'address')
    op.drop_column('venue', 'image_link')
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('facebook_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('image_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website1')
    op.drop_column('venue', 'image_link1')
    op.drop_column('venue', 'facebook_link1')
    op.drop_column('venue', 'address1')
    op.add_column('artist', sa.Column('facebook_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('image_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website1')
    op.drop_column('artist', 'image_link1')
    op.drop_column('artist', 'facebook_link1')
    op.drop_column('artist', 'address1')
    # ### end Alembic commands ###
