"""empty message

Revision ID: 2351cabed79c
Revises: c9230cdce310
Create Date: 2020-05-08 13:23:28.180392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2351cabed79c'
down_revision = 'c9230cdce310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time1', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time1')
    # ### end Alembic commands ###
