"""empty message

Revision ID: 8855b9b5d623
Revises: 97b12e4726d3
Create Date: 2020-05-08 12:17:46.625265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8855b9b5d623'
down_revision = '97b12e4726d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shows')
    op.drop_column('artist', 'address')
    op.drop_column('artist', 'facebook_link')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'phone')
    op.drop_column('artist', 'website')
    op.drop_column('venue', 'address')
    op.drop_column('venue', 'facebook_link')
    op.drop_column('venue', 'image_link')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'phone')
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('image_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('facebook_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('image_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('facebook_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('shows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='shows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='shows_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shows_pkey')
    )
    op.drop_table('show')
    # ### end Alembic commands ###
