"""empty message

Revision ID: 9ebcc30ebd79
Revises: f12b06258596
Create Date: 2020-05-08 23:55:34.566575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebcc30ebd79'
down_revision = 'f12b06258596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.String(length=10), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('state', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###
