"""empty message

Revision ID: a1fa5642f136
Revises: 53407bee1b06
Create Date: 2020-05-06 16:31:36.479704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fa5642f136'
down_revision = '53407bee1b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('city', sa.String(length=10), nullable=False))
    op.add_column('artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('state', sa.String(length=2), nullable=False))
    op.alter_column('genres_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('genres_artist', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('genres_venue', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('genres_venue', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows_artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows_venue', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows_venue', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('venue', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('phone', sa.String(length=120), nullable=True))
    op.alter_column('venue', 'city',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('venue', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('venue', 'city',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('venue', 'phone')
    op.drop_column('venue', 'image_link')
    op.drop_column('venue', 'facebook_link')
    op.drop_column('venue', 'address')
    op.alter_column('shows_venue', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shows_venue', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shows_artist', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('shows_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genres_venue', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genres_venue', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genres_artist', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('genres_artist', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'phone')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'facebook_link')
    op.drop_column('artist', 'city')
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
