"""empty message

Revision ID: a7f716aba81d
Revises: 8855b9b5d623
Create Date: 2020-05-08 12:46:50.313908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f716aba81d'
down_revision = '8855b9b5d623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('facebook_link', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('image_link', sa.String(length=100), nullable=True))
    op.add_column('artist', sa.Column('phone', sa.String(length=10), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=100), nullable=True))
    op.add_column('venue', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('venue', sa.Column('facebook_link', sa.String(length=100), nullable=True))
    op.add_column('venue', sa.Column('image_link', sa.String(length=100), nullable=True))
    op.add_column('venue', sa.Column('phone', sa.String(length=10), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'phone')
    op.drop_column('venue', 'image_link')
    op.drop_column('venue', 'facebook_link')
    op.drop_column('venue', 'address')
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'phone')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'facebook_link')
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
