"""empty message

Revision ID: c4d535e59c0a
Revises: d5350c72cfe4
Create Date: 2020-05-08 17:37:26.540158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d535e59c0a'
down_revision = 'd5350c72cfe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
