"""empty message

Revision ID: d5350c72cfe4
Revises: f95f6d2a5f2c
Create Date: 2020-05-08 17:37:04.961595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5350c72cfe4'
down_revision = 'f95f6d2a5f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time1', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time1')
    # ### end Alembic commands ###
