"""empty message

Revision ID: d8d16ad1b653
Revises: 31e942e51bdb
Create Date: 2020-05-08 13:24:10.027542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d16ad1b653'
down_revision = '31e942e51bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(length=50), nullable=True))
    op.drop_column('show', 'start_time1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
